-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================
-- USER
-- ============================
CREATE TABLE IF NOT EXISTS "user" (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active        BOOLEAN NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    external_id   UUID NOT NULL,
    updated_at    TIMESTAMP(6),
    email         VARCHAR(255),

    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_external UNIQUE (external_id)
);

-- ============================
-- ORGANIZATION
-- ============================
CREATE TABLE IF NOT EXISTS organization (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active        BOOLEAN NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    external_id   UUID NOT NULL,
    updated_at    TIMESTAMP(6),
    code          VARCHAR(255),
    image_path    VARCHAR(255),
    name          VARCHAR(255),

    CONSTRAINT organization_pkey PRIMARY KEY (id),
    CONSTRAINT uk_organization_external UNIQUE (external_id)
);

-- ============================
-- STATEMENT
-- ============================
CREATE TABLE IF NOT EXISTS statement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active          BOOLEAN NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    external_id     UUID NOT NULL,
    updated_at      TIMESTAMP(6),
    account         VARCHAR(255),
    currency        VARCHAR(255) NOT NULL,
    final_date      TIMESTAMP(6) NOT NULL,
    initial_date    TIMESTAMP(6) NOT NULL,
    organization_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,

    CONSTRAINT statement_pkey PRIMARY KEY (id),
    CONSTRAINT uk_statement_external UNIQUE (external_id)
);

-- ============================
-- STATEMENT EMBEDDING
-- ============================
CREATE TABLE IF NOT EXISTS statement_embedding (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active        BOOLEAN NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    external_id   UUID NOT NULL,
    updated_at    TIMESTAMP(6),
    content       TEXT,
    statement_id  BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    vector        VECTOR(1536),

    CONSTRAINT statement_embedding_pkey PRIMARY KEY (id),
    CONSTRAINT uk_statement_embedding_external UNIQUE (external_id)
);

-- ============================
-- INSIGHT
-- ============================
CREATE TABLE IF NOT EXISTS insight (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active        BOOLEAN NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    external_id   UUID NOT NULL,
    updated_at    TIMESTAMP(6),
    critic        TEXT NOT NULL,
    praise        TEXT NOT NULL,
    statement_id  BIGINT,
    user_id       BIGINT NOT NULL,

    CONSTRAINT insight_pkey PRIMARY KEY (id),
    CONSTRAINT uk_insight_statement UNIQUE (statement_id),
    CONSTRAINT uk_insight_external UNIQUE (external_id)
);

-- ============================
-- TRANSACTION
-- ============================
CREATE TABLE IF NOT EXISTS transaction (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active                BOOLEAN NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    external_id           UUID NOT NULL,
    updated_at            TIMESTAMP(6),
    category              VARCHAR(255) NOT NULL,
    data                  TIMESTAMP(6) NOT NULL,
    description           VARCHAR(255) NOT NULL,
    name                  VARCHAR(255),
    statement_id          BIGINT NOT NULL,
    type                  VARCHAR(255),
    value                 NUMERIC(38, 2) NOT NULL,
    reference_original_id BIGINT,

    CONSTRAINT transaction_pkey PRIMARY KEY (id),
    CONSTRAINT uk_transaction_external UNIQUE (external_id),
    CONSTRAINT transaction_type_check CHECK (
        type IN ('CREDIT', 'DEBIT')
    )
);

CREATE INDEX IF NOT EXISTS idx_statement_embedding_vector_hnsw
ON statement_embedding
USING hnsw (vector vector_cosine_ops);